### PR TITLE
Second Meetup Bangalore Chapter

### PR DESCRIPTION
**Pull request by nishankvboy**
This is the second machine learning meetup post in the Bangalore Chapter. This post contains the description of happenings and 6 images from the meetup.

### CODE REVIEW

**Comment by harshnisar** [comment]
@nishankvboy 
Thanks for the pull.

Can you put in a small paragraph to what you are sending in?
Eg. Second post for meetup - post added etc etc.

And link to your local setup so I can do some basic testing before merging.

**Comment by nishankvboy** [comment]
@harshnisar 
following is the link to the local setup 
https://github.com/nishankvboy/ml-india/tree/gh-pages/_posts

I have added a small description. pls check and let me know if its insufficient and how detailed it needs to be. 
Thanks

**Comment by harshnisar** [comment]
cc: @bhanu-mnit 

@nishankvboy 
Seems fine. Do you think we can use a better excerpt to the post? 

Excerpts are used to generate the summary at the homepage and also used by Google as meta data for search ranking. 

I think the /ml-chapter will also need to be updated. You can add the same changes in this commit and I'll merge thereafter.

http://ml-india.org/ml-chapter/#bangalore

**Comment by harshnisar** [comment]
Squashed and merged. :+1: 

Live.

**Comment by nishankvboy** [comment]
great. thanks

**Pull request merged**
